# Theme
import = [ "~/.config/alacritty/themes/themes/snazzy.toml" ]

[window]
padding = { x = 7, y = 7 }
dynamic_padding = true
decorations_theme_variant = "Dark"

[font]
size = 13
normal = { family = "Jetbrains Mono", style = "Light" }
bold = { style = "Regular" }

[cursor]
style = {blinking = "On"}

[mouse]
hide_when_typing = true
